### ISSUE TITLE
Data for GUI Examples

### ISSUE THREAD

**Issue by tedjohnson12** [ortk95/planetmapper#271]
Hi, I am creating this issue as part of the JOSS review process.
I really like the `planetmapper` page on readthedocs, but I think it could benefit from a sample dataset that new users could download and use with the GUI. I see all of the API examples can be created using the code in `examples/`, but perhaps you could add an `examples/data` directory with the images of Europa from Earth (or a toy version if those data are proprietary or extremely large). I think that could provide enormous benefit to new users. Thanks!

**Comment by ortk95** [comment]
While doing this, it might be worth explicitly listing the full set of kernels needed to run the GUI examples somewhere in the documentation to help make stuff easier for new users

**Comment by ortk95** [comment]
Added Europa FITS file in ef274ee. Still need to

- [ ] Add a bit more useful info to README - e.g. link back to readthedocs documentation
- [ ] Add link from docs to the example data

**Comment by ortk95** [comment]
Added example dataset in https://github.com/ortk95/planetmapper/tree/main/examples/gui_data and link to this dataset in https://planetmapper.readthedocs.io/en/latest/user_interface.html#fitting-an-observation
