### ISSUE TITLE
Docu suggestions

### ISSUE THREAD

**Issue by steo85it** [ortk95/planetmapper#280]
The docs look great, very thorough and complete. I just have several minor suggestions:
- [x] In the wire-frame plot [example](https://planetmapper.readthedocs.io/en/latest/general_python_api.html), include the necessary kernels (de430 and leapseconds are not enough for even basic ones, e.g.,  `body = planetmapper.Body('saturn', '2020-01-01')`, probably because of its satellites - Saturn != Saturn Barycenter). As an alternative, use Mercury or Venus for such simple examples. 
- [x] all examples regarding the attached europa.fits indicate europa.fits.gz (minor, still works with the uncompressed file)
- [x] include all necessary imports (planetmapper, pyplot) in the examples to facilitate the "copy/paste" by beginner users

[joss](https://github.com/openjournals/joss-reviews/issues/5728)

**Comment by ortk95** [comment]
> all examples regarding the attached europa.fits indicate europa.fits.gz (minor, still works with the uncompressed file)

Updated paths in 969bd2aa4aa679854a7a2094dfefbde002156ece

**Comment by ortk95** [comment]
>  include all necessary imports (planetmapper, pyplot) in the examples to facilitate the "copy/paste" by beginner users

Added imports in a2bb51bac181846eed05d5512c530b8c4fa602ad

**Comment by ortk95** [comment]
>In the wire-frame plot [example](https://planetmapper.readthedocs.io/en/latest/general_python_api.html), include the necessary kernels (de430 and leapseconds are not enough for even basic ones, e.g., body = planetmapper.Body('saturn', '2020-01-01'), probably because of its satellites - Saturn != Saturn Barycenter). As an alternative, use Mercury or Venus for such simple examples.

Documented the kernels needed to run the examples, and added a code snippet to download the required kernels in fb3606862f3227a64530ffe7fc110f96d68cdd10

**Comment by ortk95** [comment]
https://planetmapper.readthedocs.io/en/dev/general_python_api.html now documents the required kernels, includes imports for all code snippets and uses consistent filenames with the example data file
