### ISSUE TITLE
Code and testing

### ISSUE THREAD

**Issue by steo85it** [ortk95/planetmapper#282]
All examples and tests seem to run ok, installation works well both via pip or git clone.
However:
- [x] `./run_checks.sh` within the cloned dir results in a `black command not found` error. Am I doing something wrong?
- [x] `examples/make_logos.py` does not work with only the basic recommended kernels, see #280  (it should at least be documented which ones are needed)

[joss](https://github.com/openjournals/joss-reviews/issues/5728)

**Comment by ortk95** [comment]
> ./run_checks.sh within the cloned dir results in a black command not found error. Am I doing something wrong?

The developemnt dependencies were never actually documented anywhere. I've now added an explicit `dev_requirements.txt` file, so all the development dependencies can be installed with `pip install -r dev_requirements.txt`. Also added associated documentation to signpost this.

66ab80b228e9197599fa6e142c7ef6cfa12c5551:

**Comment by ortk95** [comment]
> examples/make_logos.py does not work with only the basic recommended kernels, see https://github.com/ortk95/planetmapper/issues/280 (it should at least be documented which ones are needed)

Added required kernels (& script to download them) in 110719ce0815c1f1a1ca82bf468afda8f243b1b1
